import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_uicomponents/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="relative w-[100vw]] flex min-h-[100vh]">
        <Sidebar />
        <div className="w-[1200px] ">
          {children}
        </div>
      </body>
    </html>
  );
}
